website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    login_status = None  

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.objects(email=email).first()
        if user and check_password_hash(user.password, password):
            login_user(user, remember=True)
            login_status = 'success'
            return redirect(url_for('views.home', id=user.id))
        else:
            login_status = 'failure'
    
    print(login_status)
    return render_template("login.html", user=current_user, login_status=login_status)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    error_message = None
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.objects(email=email).first()  
        if user:
            error_message = 'Email already exists.'
        elif len(email) < 4:
            error_message = 'Email must be greater than 3 characters.'
        elif len(name) < 2:
            error_message = 'First name must be greater than 1 character.'
        elif password1 != password2:
            error_message = 'Passwords don\'t match.'
        elif len(password1) < 4:
            error_message = 'Password must be at least 4 characters.'
        else:
            hashed_password = generate_password_hash(password1, method='pbkdf2:sha256')
            new_user = User(email=email, name=name, password=hashed_password)

            new_user.save()  # Save the new user to the MongoDB collection
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
        
    print(error_message)

    return render_template("login.html", user=current_user, error_message=error_message)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify,redirect, url_for
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
import os
from .models import Note
from . import db
import json
from datetime import date


views = Blueprint('views', __name__)


# HOME PAGE
@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)


# YOUR SPORTS PAGE
@views.route('/your_sports', methods=['GET', 'POST'])
@login_required
def your_sports():
    # Get the user's sports field
    sports = current_user.data['sports']
    return render_template("your_sports.html", user=current_user, sports=sports)

@views.route('/todo_sports', methods=['GET', 'POST'])
@login_required
def add_sport():
    if request.method == 'POST':
        title = request.form.get('title')
        completed = 'completed' in request.form

        # Create a new todo dictionary
        new_todo = {'title': title, 'completed': completed}

        # Update the "sports" array in the "data" field, i want: data = db.DictField(default={'sports': [], 'gallery': [], 'calendar': []})
        current_user.update(push__data__sports=new_todo)
        
        flash('Sport added!', category='success')       
        
        return redirect(url_for('views.your_sports'))

    return render_template("your_sports.html", user=current_user)

@views.route('/delete_sport', methods=['GET', 'POST'])
def delete_sport():
    sport_title = request.args.get('title')
    current_user.update(pull__data__sports__title=sport_title)
    return redirect(url_for('views.your_sports'))
  
@views.route('/update_sports', methods=['GET', 'POST'])
def update_sports():
    if request.method == 'POST':
        print("POST")
        return redirect(url_for('views.your_sports'))

    return redirect(url_for('views.your_sports'))


# NOTES PAGE
@views.route('/notes', methods=['GET', 'POST'])
@login_required
def notes():
    if request.method == 'POST': 
        note_text = request.form.get('note')

        if len(note_text) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note_text, user=current_user)
            new_note.save()

            # Update the user's notes field
            current_user.update(push__notes=new_note)

            flash('Note added!', category='success')
            
            # Redirect to the same page after a successful POST
            return redirect(url_for('views.notes'))

    return render_template("notes.html", user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():  
    note_data = json.loads(request.data)
    note_id = note_data['noteId']

    try:
        note = Note.objects.get(id=note_id)
        print(note_id)
        
        # delete the note from the user's notes field
        current_user.update(pull__notes=note)
        note.delete()
        return jsonify({'success': True})

    except Note.DoesNotExist:
        print("DOESNOTEXIST")
        return jsonify({'success': False, 'error': 'Note not found'})
    except Exception as e:
        print("lol")
        return jsonify({'success': False, 'error': str(e)})


# GALLERY PAGE
@views.route('/gallery', methods=['GET', 'POST'])
@login_required
def gallery():
    return render_template("gallery.html", user=current_user)

@views.route('/add_to_gallery', methods=['GET', 'POST'])
@login_required
def add_to_gallery():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        image = request.files['image']

        filename = secure_filename(image.filename)
        image.save(os.path.join('website/static/img/uploaded_files', filename))
        
        new_image = {'title': title, 'description': description, 'image': filename}
        current_user.update(push__data__gallery=new_image)
        
        flash('Image added!', category='success')
        return redirect(url_for('views.gallery'))
    return render_template("gallery.html", user=current_user)

@views.route('/delete_gallery_image', methods=['GET', 'POST'])
def delete_gallery_image():
    image_title = request.args.get('title')
    print(image_title)
    current_user.update(pull__data__gallery__title=image_title)
    return redirect(url_for('views.gallery'))


# CALENDAR PAGE
@views.route('/calendar', methods=['GET', 'POST'])
@login_required
def calendar():
    time = date.today()
    
    day = time.strftime("%A")
    
    return render_template("calendar.html", user=current_user, day=day)

@views.route('/add_event', methods=['GET', 'POST'])
@login_required
def add_event():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        date = request.form['due_date']
        repeat_option = request.form['repeat_option']
        
        new_event = {'title': title, 'description': description, 'date': date, 'repeat_option': repeat_option}
        
        # Check if the title contains "surf"
        if 'kitesurf' in title.lower() or 'kiteboarding' in title.lower() or 'kite' in title.lower():
            new_event['image_path'] = '/img/kitesurf.jpg'
        elif 'surf' in title.lower() or 'surfing' in title.lower():
            new_event['image_path'] = '/img/surf.jpg'
        elif 'skate' in title.lower() or 'skating' in title.lower():
            new_event['image_path'] = '/img/skate.jpg'
        elif 'bike' in title.lower() or 'biking' in title.lower():
            new_event['image_path'] = '/img/bike.jpg'
        elif 'football' in title.lower() or 'soccer' in title.lower() or 'futebol' in title.lower() or 'fútebol' in title.lower():
            new_event['image_path'] = '/img/roni.jpg'
        
        current_user.update(push__data__calendar=new_event)
        
        flash('Event added!', category='success')
        return redirect(url_for('views.calendar'))
    
    return render_template("calendar.html", user=current_user)

@views.route('/delete_calendar_event', methods=['GET', 'POST'])
def delete_calendar_event():
    event_title = request.args.get('title')
    current_user.update(pull__data__calendar__title=event_title)
    return redirect(url_for('views.calendar'))


# PROFILE PAGE
@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    return render_template("profile.html", user=current_user)

@views.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    if request.method == 'POST':
        # Check if the form data exists before accessing it
        email = request.form.get('email', current_user.email)
        name = request.form.get('name', current_user.name)
        contact = request.form.get('contact', current_user.contact)
        country = request.form.get('country', current_user.country)
        
        current_user.update(email=email, name=name, contact=contact, country=country)
        
        flash('Profile updated!', category='success')
        return redirect(url_for('views.profile'))
    
    return render_template("profile.html", user=current_user)

@views.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    current_password = request.form.get('currentPassword')
    new_password = request.form.get('newPassword')
    confirm_password = request.form.get('confirmPassword')

    if not current_user.check_password(current_password):
        print("Wrong password, try again!")
        flash('Wrong password, try again!', category='error')
    elif new_password != confirm_password:
        print("Passwords don't match!")
        flash('Passwords don\'t match!', category='error')
    else:
        print("Password changed successfully!")
        current_user.set_password(new_password)
        current_user.update(password=current_user.password_hash)

    flash('Password changed successfully!', category='success')
    return redirect(url_for('views.profile'))

@views.route('/delete_account', methods=['GET', 'POST'])
@login_required
def delete_account():
    current_user.delete()
    return redirect(url_for('auth.logout'))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>
    {% block title %}
    OutSports
    {% endblock %}
  </title>
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/boxicons/2.0.7/css/boxicons.min.css">


</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
        class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text" id="navbar-username"></span>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="/your_sports">My Sports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/notes">Notes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/calendar">Calendar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/gallery">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/profile"><i class="fa-solid fa-user"></i> {{user.name}} </a>
        </li>
        {% endif %}
        

      </ul>
    </div>
  </nav>

  <div class="container">{% block content %} {% endblock %}</div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/2581def8d6.js" crossorigin="anonymous"></script>
  <script  href="{{ url_for('static', filename='js/script.js') }}" defer></script>

</body>

</html>

website/templates/calendar.html
{% extends "base.html" %}

{% block content %}
<div class="container my-1">
    <h2 class="title">OutSports</h2>
</div>

<div class="container my-2">
    <div class="row">
        <div class="col-md-6">
            <div class="section-title">
                <h2>Calendar</h2>
                <p>Sports Calendar</p>
            </div>
        </div>
        <div class="col-md-6 text-right">
            <div class="addEvent-container">
                <button type="button" class="btn btn-lg addEvent-btn" data-bs-toggle="modal" data-bs-target="#addEventModal">
                    Add Event
                </button>
            </div>
        </div>
    </div>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/calendar.css') }}">

    <!-- Display Calendar -->
    <div class="calendar">
        {% for event in user.data.calendar %}


            <div class="event-card">
                <a href="{{ url_for('views.delete_calendar_event', title=event.title) }}" class="remove-button" onclick="return confirm('Are you sure you want to delete {{ event.title }}?')">X</i></a>
                <div class="card-header">
                    <h3>{{ event.title }}</h3>
                    {% if event.date %}
                        <p>Due Date: {{ event.date }}</p>
                    {% endif %}
                    {% if event.repeat_option == 'every_week' %}
                        <p>Repeat: Every {{ day }} </p>
                    {% elif event.get_repeat_option_display %}
                        <p>Repeat: {{ event.get_repeat_option_display }}</p>
                    {% endif %}
                </div>
                
                <div class="card-body">
                    <p>{{ event.description }}</p>
                </div>
                <div class="card-footer">
                    {% if 'image_path' in event %}
                        <img src="{{ url_for('static', filename=event.image_path) }}" alt="{{ event.title }}">
                    {% endif %}
                </div>
            </div>

        {% endfor %}
    </div>
    

   <!--MODAL NEW EVENT-->
    <div class="modal fade" id="addEventModal" tabindex="-1" aria-labelledby="addEventModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="addEventModalLabel">Add Event</h1>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>                
                <div class="modal-body">
                    <form method="post" action="{{ url_for('views.add_event') }}">

                        <!-- Event Title -->
                        <div class="mb-3">
                            <label for="id_title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="id_title" name="title" required>
                        </div>
                        
                        <!-- Event Description -->
                        <div class="mb-3">
                            <label for="id_description" class="form-label">Description</label>
                            <textarea class="form-control" id="id_description" name="description" rows="3"></textarea>
                        </div>
                        
                        <!-- Event Due Date -->
                        <div class="mb-3">
                            <label for="id_due_date" class="form-label">Due Date</label>
                            <input type="date" class="form-control" id="id_due_date" name="due_date" required>
                        </div>
                        
                        <!-- Event Repeat Option -->
                        <div class="mb-3">
                            <label for="id_repeat_option" class="form-label">Repeat Option</label>
                            <select class="form-select" id="id_repeat_option" name="repeat_option" required>
                                <option value="" selected disabled>Select Repeat Option</option>
                                <option value="never">Never</option>
                                <option value="every_day">Every Day</option>
                                <option value="every_week">Every Week</option>
                                <option value="every_two_weeks">Every Two Weeks</option>
                                <option value="every_month">Every Month</option>
                                <option value="every_year">Every Year</option>
                            </select>
                        </div>
                        
                        <div class="modal-footer d-flex justify-content-center"> 
                            <button type="submit" class="btn btn-primary">Add Event</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

website/templates/gallery.html
{% extends "base.html" %} {% block content %}
<div class="container my-1">
  <h2 class="title">OutSports</h2>
</div>

<div class="container my-2">
  <div class="row">
    <div class="col-md-6">
      <div class="section-title">
        <h2>Gallery</h2>
        <p>My Sports Gallery</p>
      </div>
    </div>
    <div class="col-md-6 text-right">
      <div class="addEvent-container">
        <a
          href=""
          class="btn btn-lg addEvent-btn"
          data-bs-toggle="modal"
          data-bs-target="#addImageModal"
        >
          Add Image
        </a>
      </div>
    </div>
  </div>

  <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static', filename='css/gallery.css') }}"
  />

  <section id="portfolio" class="portfolio">
    <div class="container" data-aos="fade-up">
      <div
        class="row portfolio-container"
        data-aos="fade-up"
        data-aos-delay="200"
      >
        {% for image in user.data.gallery %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
          <div class="portfolio-wrap">
            <img
              src="{{ url_for('static', filename='img/uploaded_files/' + image.image) }}"
              alt="{{ image.title }}"
            />
            <div class="portfolio-info">
              <h4>{{ image.title }}</h4>
              <p>{{ image.description }}</p>
              <div class="portfolio-links">
                <a
                  href="{{ url_for('static', filename='img/uploaded_files/' + image.image) }}"
                  data-gallery="portfolioGallery"
                  class="portfolio-lightbox"
                  title="{{ image.title }}"
                  ><i class="bx bx-plus"></i
                ></a>
                <a
                  href="{{ url_for('views.delete_gallery_image', title=image.title) }}"
                  class="remove-button"
                  onclick="return confirm('Are you sure you want to delete <{{ image.title }}> image?')"
                >
                  <i
                    class="fa-solid fa-trash"
                    style="font-size: 0.8em; position: flex; top: 0; left: 0"
                  ></i>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</div>

<!-- Add Image Modal -->
<div
  class="modal fade"
  id="addImageModal"
  tabindex="-1"
  aria-labelledby="addImageModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addImageModalLabel">Add Image</h5>
        <button
          type="button"
          class="close"
          data-bs-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form
          method="post"
          action="{{ url_for('views.add_to_gallery') }}"
          enctype="multipart/form-data"
        >
          <label for="id_title">Title:</label>
          <input
            type="text"
            class="form-control"
            id="id_title"
            name="title"
            required
          />

          <label for="id_description">Description:</label>
          <textarea
            class="form-control"
            id="id_description"
            name="description"
          ></textarea>

          <label for="id_image">Image:</label>
          <input
            type="file"
            class="form-control"
            id="id_image"
            name="image"
            accept="image/*"
            required
          />

          <button type="submit" class="btn btn-primary float-right">
            Add Image
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

website/templates/notes.html
{% extends "base.html" %} {% block title %}Notes{% endblock %} {% block content
%}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    {{ note.data }}
    <button type="button" class="close" onClick="deleteNote('{{ note.id }}')">
      <span aria-hidden="true">&times;</span>
    </button>    
    <button type="button" class="close" onClick="deleteNote('{{ note.id }}', '{{ note.data }}')">

  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>

{% block javascript %}
<script type="text/javascript">

  function deleteNote(noteId, noteData) {
    console.log('Deleting note with ID:', noteId);
  
    fetch("/delete-note", {
      method: "POST",
      body: JSON.stringify({ noteId: noteId, noteData: noteData }),
    }).then((res) => {
      if (!res.ok) {
        throw new Error(`Failed to delete note. Status: ${res.status}`);
      }
      return res.json();
    }).then((data) => {
      if (data.success) {
        console.log('Note deleted successfully');
        // You may want to remove the note from the UI here
        window.location.href = "/notes";
      } else {
        console.error('Error deleting note:', data.error);
        // Handle the error as needed
      }
    }).catch((error) => {
      console.error('Error:', error);
    });
  }
  
  

  
</script>
{% endblock %}

{% endblock %}

website/templates/your_sports.html
{% extends "base.html" %} {% block title %}Sports List{% endblock %} {% block
content %}
<div class="container my-1">
  <h2 class="title">OutSports</h2>
</div>

<div class="container my-2">
  <div class="container my-1">
    <div class="section-title">
      <h2>sportS</h2>
      <p>Sports List sportS</p>
    </div>

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/todos.css') }}"
    />

    {% if sports %}
    <div class="container my-1 d-flex justify-content-center">
      <form
        method="post"
        action="{{ url_for('views.update_sports') }}"
        id="updateForm"
      >
        <div class="container my-5">
          <ul id="sport-list">
            {% for sport in sports %}
            <li>
              <input type="hidden" name="sport_ids[]" value="{{ sport.id }}" />
              <input
                type="checkbox"
                name="completed[{{ sport.id }}]"
                {%
                if
                sport.completed
                %}checked{%
                endif
                %}
                value="{{ sport.id }}"
              />
              <span
                id="sportTitle_{{ sport.id }}"
                name="names[{{ sport.id }}]"
                class="sport-title"
                >{{ sport.title }}</span
              >

              <!-- Add hidden input fields for title and completed -->
              <input type="hidden" name="titles[]" value="{{ sport.title }}" />
              <input
                type="hidden"
                name="statuses[]"
                value="{{ sport.completed }}"
              />

              <div class="button-container">
                <a
                  href="#"
                  class="btn btn-primary btn-sm edit-button"
                  onclick="editSport('{{ sport.id }}', '{{ sport.title }}')"
                >
                  <i class="fa-sharp fa-solid fa-pen-to-square"></i>
                </a>

                <a
                  href="{{ url_for('views.delete_sport', title=sport.title) }}"
                  class="btn btn-danger btn-sm"
                  onclick="return confirm('Are you sure you want to delete {{ sport.title }}?')"
                >
                  <i class="fa-solid fa-trash"></i>
                </a>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
        <div class="button-container">
          <button type="submit" class="btn btn updateButton">Update</button>
          <button
            type="button"
            class="btn btn addToListButton"
            data-bs-toggle="modal"
            data-bs-target="#exampleModal"
          >
            Add to List
          </button>
        </div>
      </form>
    </div>
    {% else %}
    <div class="empty-list-message text-center">
      <p>
        No sports in the list. Add your favorite sports!
        <i class="far fa-smile"></i>
      </p>
      <div class="container my-2">
        <img
          src="{{ url_for('static', filename='img/kitesurf.jpg') }}"
          alt="Empty List Image"
          class="img-fluid"
          style="height: 420px"
        />
      </div>

      <button
        type="button"
        class="btn btn addToListButton"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal"
        style="scale=0.5"
      >
        Add to List
      </button>
    </div>
    {% endif %}

    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Add to List</h1>
            <button
              type="button"
              class="close"
              data-bs-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form
              id="addToListForm"
              method="post"
              action="{{ url_for('views.add_sport') }}"
            >
              <div class="mb-3">
                <label for="id_title" class="form-label">Title</label>
                <input
                  type="text"
                  class="form-control"
                  id="id_title"
                  name="title"
                />
              </div>
              <div class="mb-3 form-check">
                <input
                  type="checkbox"
                  class="form-check-input"
                  id="id_completed"
                  name="completed"
                />
                <label class="form-check-label" for="id_completed"
                  >Completed</label
                >
              </div>
              <div class="modal-footer d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">
                  Add to List
                </button>
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  Close
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script></script>

{% endblock %}